/*
  app.js -- This creates an Express webserver with login/register/logout authentication
*/

// *********************************************************** //
//  Loading packages to support the server
// *********************************************************** //
// First we load in all of the packages we need for the server...
const createError = require("http-errors"); // to handle the server errors
const express = require("express");
const path = require("path");  // to refer to local paths
const cookieParser = require("cookie-parser"); // to handle cookies
const session = require("express-session"); // to handle sessions using cookies
const debug = require("debug")("personalapp:server"); 
const layouts = require("express-ejs-layouts");
const axios = require("axios")


// *********************************************************** //
// Initializing the Express server 
// This code is run once when the app is started and it creates
// a server that respond to requests by sending responses
// *********************************************************** //
const app = express();

// Here we specify that we will be using EJS as our view engine
app.set("views", path.join(__dirname, "views"));
app.set("view engine", "ejs");



// this allows us to use page layout for the views 
// so we don't have to repeat the headers and footers on every page ...
// the layout is in views/layout.ejs
app.use(layouts);

// Here we process the requests so they are easy to handle
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Here we specify that static files will be in the public folder
app.use(express.static(path.join(__dirname, "public")));

// Here we enable session handling using cookies
app.use(
  session({
    secret: "zzbbyanana789sdfa8f9ds8f90ds87f8d9s789fds", // this ought to be hidden in process.env.SECRET
    resave: false,
    saveUninitialized: false
  })
);

// *********************************************************** //
//  Defining the routes the Express server will respond to
// *********************************************************** //


// here is the code which handles all /login /signin /logout routes
const auth = require('./routes/auth');
const { deflateSync } = require("zlib");
app.use(auth)

// middleware to test is the user is logged in, and if not, send them to the login page

// specify that the server should render the views/index.ejs page for the root path
// and the index.ejs code will be wrapped in the views/layouts.ejs code which provides
// the headers and footers for all webpages generated by this app
app.get("/", (req, res, next) => {
  res.render("index");
});

app.get("/about", (req, res, next) => {
  res.render("about");
});





// Define the news data
const news = [
  { title: 'December 1922 The Formation of the Soviet Union', description: 'The Soviet Union is officially established as a federal socialist state, comprising of the Russian, Transcaucasian, Ukrainian, and Byelorussian Soviet Socialist Republics.', imageUrl: '/images/ussr.jpg', newsUrl: 'https://daily.jstor.org/the-birth-of-the-soviet-union-and-the-death-of-the-russian-revolution/'},
  { title: 'February 1943 Victory in the Battle of Stalingrad', description: 'The success of the Soviet Union in defending Stalingrad marked a major turning point in the war and was a significant blow to Nazi Germany\'s military power. ', imageUrl: '/images/stalingrad.jpg', newsUrl: 'https://www.history.com/topics/world-war-ii/battle-of-stalingrad' },
  { title: 'March 1953 The Death of Joseph Stalin', description: 'At the age of 74 Joseph Stalin died of a stroke.', imageUrl: '/images/stalindeath.jpg', newsUrl: 'https://www.smithsonianmag.com/history/true-story-death-stalin-180965119/' },
  { title: 'October 1957 The first artificial satellite, Sputnik, was launched into orbit around the Earth.', description: 'This event marked the beginning of the Space Race between the Soviet Union and the United States, and highlighted the Soviet Union\'s technological capabilities.', imageUrl: '/images/sputnik.jpg', newsUrl: 'https://www.history.com/this-day-in-history/sputnik-launched' },
  { title: 'April 1961 Soviet cosmonaut Yuri Gagarin becomes the first person to orbit the Earth.', description: 'Yuri Gagarin  orbited the Earth aboard the Vostok 1 spacecraft for 108 minutes before returning safely to Earth marking a major achievement for the Soviet Union in the Cold War space race.', imageUrl: '/images/yuri.jpg', newsUrl: 'https://www.history.com/this-day-in-history/first-man-in-space' },
  { title: 'October 1962 The Cuban Missile Crisis', description: 'The Cuban Missile Crisis was a political and military standoff between the United States and the Soviet Union.', imageUrl: '/images/cuban.jpg', newsUrl: 'https://www.history.com/topics/cold-war/cuban-missile-crisis' },
  { title: '1974 Construction of the Baikal-Amur Mainline Railway', description: 'The Baikal-Amur Mainline Railway was a major construction project designed to provide an alternate route to the Trans-Siberian Railway and stretching for over 4,000 kilometers across remote and challenging terrain in Siberia and the Far East. ', imageUrl: '/images/train.jpg', newsUrl: 'https://rusmania.com/history-baikal-amur-railway-bam' },
  { title: 'December 1979 The Soviet Union invasion of Afghanistan', description: 'The invasion was done under under the pretext of upholding the Soviet-Afghan Friendship Treaty of 1978.', imageUrl: '/images/invade.png', newsUrl: 'https://www.history.com/this-day-in-history/soviet-tanks-roll-into-afghanistan' },
  { title: '1985-Now Perestroika and Glasnost reforms under Gorbachev', description: 'These reforms aim to modernize and liberalize the Soviet Union\'s political and economic system.', imageUrl: '/images/reform.jpg', newsUrl: 'https://www.history.com/topics/cold-war/perestroika-and-glasnost' }
];

// Render the news.ejs file with the news data
app.get('/news', (req, res) => {
  res.render('news', { news });
});

app.get('/leaders', function(req, res) {
  const leaders = [
    {
      name: 'Vladimir Lenin',
      years: '1922-1924',
      description: 'Lenin was originally the leader of the Russian Soviet Federative Socialist Republic from 1917. He was one of the most important and revolutionary figures in the Soviet Union\'s history, being the founder and shaping the policies and direction of the nation for many years to come. His leadership during the start of the Soviet Union, especially in the Bolshevik Revolution and his crucial contributions to the development of Soviet socialism were all key factors in the success of the USSR.',
      policies: [
        {
          name: 'New Economic Policy (NEP)',
          description: 'A temporary policy of economic liberalization in the early Soviet Union, allowing some private enterprise and market-oriented practices.'
        },
        {
          name: 'War Communism',
          description: 'A policy implemented during the Russian Civil War that involved nationalizing industry and agriculture, and requisitioning grain from peasants to feed the Red Army.'
        }
      ],
      img:"/images/Lenin.jpg"
    },
    {
      name: 'Joseph Stalin',
      years: '1924-1953',
      description: 'Stalin was one of the strongest and most decisive leaders in the nation\'s history, serving as its General Secretary. He led the Soviet Union through the difficult period of World War II, overseeing the country\'s military efforts, leading to the great successful defense of Stalingrad in 1942-43, and later helping to shape its post-war political landscape. These post-war policies transformed the Soviet Union from a largely agricultural nation into an industrial powerhouse, modernizing the country and improving the lives of its citizens.',
      policies: [
        {
          name: 'Five-Year Plans',
          description: 'A series of centrally planned economic policies that aimed to rapidly industrialize the Soviet Union.'
        },
        {
          name: 'Collectivization',
          description: 'A policy of forcibly consolidating individual farms into large collective farms, often resulting in violent resistance from peasants and food shortages.'
        }
      ],
      img:"/images/Stalin.jpg"
    },
    {
      name: 'Georgy Malenkov',
      years: '1953-1955',
      description: 'Georgy Malenkov was a prominent Soviet politician who served as the Premier of the Soviet Union for a brief period of time.  During his time as the Premier, Malenkov oversaw the Soviet Union\'s first hydrogen bomb test and the launch of the first Soviet nuclear submarine. He also initiated a number of economic reforms, including the decentralization of economic planning and the liberalization of small-scale private enterprise.',
      policies: [],
      img:"/images/Malenkov.jpg"
    },
    {
      name: 'Nikita Khrushchev',
      years: '1955-1964',
      description: 'Nikita Khrushchev was a prominent political figure, serving as the First Secretary of the Communist Party of the Soviet Union. He was best known as a reformer who aimed to modernize the Soviet Union, improve the standard of living for its citizens, and reduce the country\'s reliance on Stalin-era policies and practices.',
      policies: [
        {
          name: 'Virgin Lands Campaign',
          description: 'A policy of encouraging farmers to cultivate previously unused lands in Kazakhstan and Siberia, which led to significant increases in grain production.'
        },
        {
          name: 'Thaw',
          description: 'A period of greater political and cultural openness in the Soviet Union, following the repressive policies of Stalin.'
        }
      ],
      img:"/images/Khrushchev.jpg"
    },
    {
      name: 'Leonid Brezhnev',
      years: '1964-1982',
      description: 'Leonid Brezhnev served as the General Secretary of the Communist Party of the Soviet Union. He was a strong leader who made significant contributions to the Soviet Union during his tenure. He oversaw the signing of several important arms control treaties with the United States, including the Strategic Arms Limitation Treaty (SALT) and the Anti-Ballistic Missile Treaty (ABM). These agreements helped to reduce tensions between the two superpowers and to decrease the likelihood of nuclear war. Economically he maintained the policies of his predecessor, Khrushchev, by focusing on improvements to the Soviet economy and standard of living for its citizens. His policies were largely successful, and under his leadership, the Soviet Union experienced a period of sustained economic growth and stability.',
      policies: [
        {
          name: 'Brezhnev Doctrine',
          description: 'A policy of intervention in the affairs of other socialist countries to maintain their alignment with the Soviet Union.'
        },
        {
          name: '1977 Soviet Constitution',
          description: 'A revised constitution that included many liberalizing reforms, but also enshrined the Communist Party\'s monopoly on power and limited individual rights.'
        }
      ],
      img:"/images/Brezhnev.jpg"
    },
    {
      name: 'Yuri Andropov',
      years: '1982-1984',
      description: 'Yuri Andropov briefly served as the General Secretary of the Communist Party of the Soviet Union. Andropov worked to combat corruption within the party and government and attempted to address economic issues facing the Soviet Union. Although his tenure was greatly shortened due to his illness, he still helped pave the way for the modernization of the USSR.',
      policies: [],
      img:"/images/Andropov.jpg"
    },
    {
      name: 'Konstantin Chernenko',
      years: '1984-1985',
      description: 'Konstantin Chernenko was a Soviet politician who served as General Secretary of the Communist Party of the Soviet Union for a short period of time. As General Secretary, Chernenko was known for his opposition to reforms and continuation of the Soviet policy of arms buildup and Cold War confrontation with the West, resisting calls for greater openness and democratization.',
      policies: [],
      img:"/images/Chernenko.png"
    },
    {
      name: 'Mikhail Gorbachev',
      years: '1985-Now',
      description: 'Mikhail Gorbachev is the current President of the Soviet Union. Gorbachev\'s economic reforms aim to decentralize the Soviet economy, giving more autonomy to enterprises and introducing market mechanisms. This is a significant departure from the centrally planned economy that had been in place for decades but is important to help modernize the country.',
      policies: [
        {
          name: 'Perestroika',
          description: 'A policy of economic restructuring that aimed to decentralize economic decision-making and encourage market-oriented reforms.'
        },
        {
          name: 'Glasnost',
          description: 'A policy of political openness that allowed for greater freedom of speech and the press, and included the release of political prisoners.'
        }
      ],
      img:"/images/Gorbachev.jpg"
    }
  ];
  res.render('leaders', { leaders });
});

app.set('view engine', 'ejs');

// Define a route to render the history page
app.get('/history', (req, res) => {
  res.render('history');
});
app.get('/credits', (req, res) => {
  res.render('credits');
});

//app.use(isLoggedIn)
// here we catch 404 errors and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// this processes any errors generated by the previous routes
// notice that the function has four parameters which is how Express indicates it is an error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get("env") === "development" ? err : {};
  // render the error page
  res.status(err.status || 500);
  res.render("error");
});


// *********************************************************** //
//  Starting up the server!
// *********************************************************** //
//Here we set the port to use between 1024 and 65535  (2^16-1)
const port = process.env.PORT || "2345";
app.set("port", port);

// and now we startup the server listening on that port
const http = require("http");
const server = http.createServer(app);

server.listen(port);

function onListening() {
  var addr = server.address();
  var bind = typeof addr === "string" ? "pipe " + addr : "port " + addr.port;
  debug("Listening on " + bind);
}

function onError(error) {
  if (error.syscall !== "listen") {
    throw error;
  }

  var bind = typeof port === "string" ? "Pipe " + port : "Port " + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case "EACCES":
      console.error(bind + " requires elevated privileges");
      process.exit(1);
      break;
    case "EADDRINUSE":
      console.error(bind + " is already in use");
      process.exit(1);
      break;
    default:
      throw error;
  }
}

server.on("error", onError);

server.on("listening", onListening);

module.exports = app;
